import { useEffect, useState } from 'react';
import { Empty, Status } from './components';
import { ClockBasis, DateCue } from './DispatchEvidence';
import { allocationTotal, amount, filterOffers, filters, projection } from './workspaceModel';
import { parseRoute, routeLink } from './routes';
import type { Workspace } from './types';

export function Records({ data, route, selected, today }: { data: Workspace; route: ReturnType<typeof parseRoute>; selected: string; today: string }) {
  const [query, setQuery] = useState(route.query);
  useEffect(() => setQuery(route.query), [route.query]);
  const rows = filterOffers(data, route.filter, route.unit, today, query);
  const units = [...new Set(projection(data).offers.map(row => row.offer.unit).filter(Boolean))].sort();
  function change(values: Partial<typeof route>) { location.hash = routeLink('/records', { offer: selected, filter: route.filter, unit: route.unit, query: route.query, ...values }).slice(1); }
  return <><div className="page-heading"><div><p className="eyebrow">OFFERS & ALLOCATION RECORDS</p><h1>Records</h1><p>{filters[route.filter]}{route.unit ? ` · ${route.unit}` : ' · All units, shown separately'}. All available offers in {data.mode}.</p></div><a href={routeLink('/workspace', { offer: selected })} className="button secondary">Return to workspace →</a></div><ClockBasis today={today}/>
    <section className="panel"><div className="toolbar record-filters"><div className="filter-field"><label htmlFor="records-search">Search offers</label><input id="records-search" type="search" value={query} onChange={event => { setQuery(event.target.value); change({ query: event.target.value }); }}/></div><div className="filter-field"><label htmlFor="records-filter">Record filter</label><select id="records-filter" value={route.filter} onChange={event => change({ filter: event.target.value as typeof route.filter })}>{Object.entries(filters).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><div className="filter-field"><label htmlFor="records-unit">Unit</label><select id="records-unit" value={route.unit} onChange={event => change({ unit: event.target.value })}><option value="">All units</option>{units.map(unit => <option key={unit}>{unit}</option>)}</select></div></div>
    {rows.length ? <div className="record-cards">{rows.map(row => { const total = allocationTotal(row); return <article key={row.offer.id}><div className="section-heading"><h2><a href={routeLink('/workspace', { offer: row.offer.id })}>{row.offer.title}</a></h2><Status value={row.status}/></div><p>{row.offer.id} · {row.offer.donor}</p><dl className="record-quantities"><div><dt>Offered</dt><dd>{Number.isFinite(row.offer.quantity) ? `${amount(row.offer.quantity)} ${row.offer.unit}` : 'Unknown'}</dd></div><div><dt>Allocated</dt><dd>{total === null ? 'Unknown' : `${amount(total)} ${row.offer.unit}`}</dd></div><div><dt>Unallocated</dt><dd>{total === null ? 'Unknown' : `${amount(row.offer.quantity - total)} ${row.offer.unit}`}</dd></div></dl><DateCue offer={row.offer} today={today} closed={!!row.plan?.recorded}/>{row.plan && <p className="small-note break-all">{row.plan.recorded ? 'Recorded allocation' : 'Draft; approval required'} · {row.plan.key}</p>}<a href={routeLink('/workspace', { offer: row.offer.id })}>Review evidence & dispatch →</a></article>; })}</div> : <Empty title="No records match">Choose another filter or <a href={routeLink('/records', { offer: selected })}>show all records</a>.</Empty>}</section>
    <p className="small-note">Allocated quantities include computed draft plans. Unknown quantities are not zero. A record does not confirm collection. Published record addresses and any supersession are in <a href={routeLink('/history', { offer: selected })}>History</a>.</p></>;
}
