import { expect, test } from '@playwright/test';
import type { Workspace } from '../src/types';

test('UX-ME-10S: cold coordinator entry to named offer, reasoned approval and separate receipt by keyboard', async ({page}, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const start = page.getByRole('region', {name: 'Your next donation'});
  await expect(start).toContainText('Collect');
  await expect(page.getByText('FOR VOLUNTEER FOOD COORDINATORS')).toBeVisible();
  await expect(start.getByRole('link', {name: 'Start with this offer →'})).toBeVisible();
  await page.screenshot({path: info.outputPath('coordinator-cold-start.png'), fullPage: true});
  // The new journey files its own offer; no historical offer is mutated.
  await page.getByRole('link', {name: '+ Add offer', exact: true}).focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('heading', {name: 'Add an offer', exact: true})).toBeVisible();
  await page.getByRole('button', {name: 'Try success', exact: true}).focus(); await page.keyboard.press('Enter');
  const title = 'Courtyard community meal vegetables';
  await page.getByLabel('What is being donated?').fill(title);
  await page.getByLabel("Donor's food and collection note").fill('Invented produce for community meals; collect before evening.');
  await page.getByLabel('Collection date', {exact: true}).fill(new Date(Date.now() + 2 * 86400_000).toISOString().slice(0, 10));
  await page.getByLabel('Use by date (if known)').fill(new Date(Date.now() + 4 * 86400_000).toISOString().slice(0, 10));
  const addResponse = page.waitForResponse(r => r.url().endsWith('/api/offers/new'));
  await page.getByRole('button', {name: 'Add to sandbox', exact: true}).focus(); await page.keyboard.press('Enter');
  const added = await addResponse; expect(added.status()).toBe(200);
  const initial: Workspace = await added.json();
  const offer = initial.offers.find(row => row.offer.title === title)!;
  expect(offer.offer.id).not.toBe('offer-4471');
  await expect(page.getByRole('heading', {name: title, exact: true})).toBeVisible();
  await page.getByRole('button', {name: 'Go to next decision ↓'}).focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('complementary', {name: 'Decision and dispatch'})).toBeFocused();
  await page.getByRole('button', {name: 'Work out the split', exact: true}).focus(); await page.keyboard.press('Enter');
  await expect(page.getByRole('heading', {name: 'Approve this exact plan', exact: true})).toBeVisible();
  const stages = page.getByRole('list', {name: 'Allocation and collection status'});
  await expect(stages).toContainText('Not approved');
  await expect(stages).toContainText('No receipt confirmed');
  await expect(page.locator('.allocation-list')).toContainText('Omonoia Soup Kitchen');
  await expect(page.locator('.allocation-list p').first()).not.toHaveText('');
  const consent = page.getByLabel('I have reviewed this exact allocation and record address, and approve this plan.');
  await consent.focus(); await page.keyboard.press('Space');
  const approvalResponse = page.waitForResponse(r => r.url().endsWith('/approve'));
  await page.getByRole('button', {name: 'Approve in sandbox', exact: true}).focus(); await page.keyboard.press('Enter');
  const approval = await approvalResponse; expect(approval.status()).toBe(200);
  const approved: Workspace = await approval.json();
  expect(approved.pickups).toHaveLength(5);
  expect(approved.pickups.every(p => p.state !== 'confirmed')).toBe(true);
  await expect(stages).toContainText('Exact allocation recorded');
  await expect(stages).toContainText('No time agreed yet');
  await expect(stages).toContainText('No receipt confirmed');
  const tasks = page.getByRole('region', {name: 'Selected offer pickups'});
  await tasks.getByRole('button', {name: 'Claim this share'}).focus(); await page.keyboard.press('Enter');
  await expect(tasks.getByText('Claimed', {exact: true})).toBeVisible();
  const when = await page.evaluate(() => { const d = new Date(Date.now() + 3600_000); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`; });
  await tasks.getByLabel('Collection time (your local time)').fill(when);
  await tasks.getByRole('button', {name: 'Save collection time'}).focus(); await page.keyboard.press('Enter');
  await expect(stages).toContainText('1 of 5 pickups scheduled');
  await expect(stages).toContainText('No receipt confirmed');
  await tasks.getByLabel('This collection actually happened in the simulation.').focus(); await page.keyboard.press('Space');
  await tasks.getByRole('button', {name: 'Confirm collection'}).focus(); await page.keyboard.press('Enter');
  await expect(stages).toContainText('1 of 5 shares confirmed in simulation');
  await page.reload();
  await expect(page.getByRole('heading', {name: title, exact: true})).toBeVisible();
  await expect(stages).toContainText('1 of 5 shares confirmed in simulation');
  await page.getByText('Pickup manifest · copy or download', {exact: true}).focus(); await page.keyboard.press('Enter');
  await expect(page.getByLabel('Pickup manifest', {exact: true})).toContainText(title);
  await expect(page.getByLabel('Pickup manifest', {exact: true})).toContainText('not a recipient receipt');
  expect(errors).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path: info.outputPath('coordinator-confirmed-handoff.png'), fullPage: true});
  await info.attach('coordinator-outcome.json', {body: JSON.stringify({offer: offer.offer, approvedDigest: approved.records[0].content_digest, humanUAT: 'NOT_RUN', scope: 'isolated synthetic API workflow; departure not tracked'}), contentType: 'application/json'});
});
