import { expect, test } from '@playwright/test';
import type { Workspace } from '../src/types';

const header = 'title,donor,quantity,unit,category,collection_date,use_by,allergens,allergens_unknown,hours_unrefrigerated,note';
const donation = (title: string, quantity = '120') => `${title},Demonstration cooperative,${quantity},kg,produce,2026-09-14,2026-09-18,,true,,Invented donation for community meals`;
const csv = [header, donation('CSV vegetables'), donation('Invalid donation', 'NaN'), donation('CSV vegetables'), donation('CSV fruit'), donation('Unselected donation')].join('\n');

test('CSV preview, cancel and selected commit use real HTTP with duplicate and refusal recovery', async ({page}, info) => {
  await page.goto('/#/offers/new');
  await page.getByText('Import a donor CSV instead', {exact: true}).click();
  const token = await page.evaluate(() => localStorage.getItem('merismos.session'));
  const read = async (): Promise<Workspace> => (await page.request.get('/api/workspace?mode=sandbox', {headers: {'X-Merismos-Session': token!}})).json();
  const before = await read();
  await page.getByLabel('Donor CSV file').setInputFiles({name: 'donors.csv', mimeType: 'text/csv', buffer: Buffer.from(csv)});
  await expect(page.getByTestId('csv-row-3')).toContainText('positive decimal');
  await expect(page.getByTestId('csv-row-4')).toContainText('Duplicate of CSV row 2');
  expect((await read()).version).toBe(before.version);
  await page.getByLabel('Select CSV row 2').check();
  await page.getByRole('button', {name: 'Cancel CSV preview'}).click();
  await expect(page.getByLabel('Select CSV row 2')).toHaveCount(0);
  expect(await read()).toEqual(before);
  await page.getByLabel('Donor CSV file').setInputFiles({name: 'donors.csv', mimeType: 'text/csv', buffer: Buffer.from(csv)});
  await page.getByLabel('Select CSV row 2').check();
  await page.getByLabel('Select CSV row 5').check();
  await expect(page.getByLabel('Select CSV row 6')).not.toBeChecked();
  await page.screenshot({path: info.outputPath('csv-preview.png'), fullPage: true});
  await page.getByRole('button', {name: 'File selected rows (2)'}).click();
  await expect(page.getByRole('heading', {name: 'CSV vegetables', exact: true})).toBeVisible();
  const after = await read();
  expect(after.offers).toHaveLength(before.offers.length + 2);
  expect(after.offers.some(o => o.offer.title === 'Unselected donation')).toBe(false);
  expect(after.records).toEqual(before.records); expect(after.pickups).toEqual(before.pickups);
  await page.getByRole('link', {name: '+ Add offer'}).click();
  await page.getByText('Import a donor CSV instead', {exact: true}).click();
  await page.getByLabel('Donor CSV file').setInputFiles({name: 'donors.csv', mimeType: 'text/csv', buffer: Buffer.from(csv)});
  await expect(page.getByTestId('csv-row-2')).toContainText('Already filed as');
  await expect(page.getByLabel('Select CSV row 2')).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('Imported offer → allocation → disruption → replan → fresh approval → simulated pickup and plain-text manifest', async ({page, context}, info) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.goto('/#/offers/new');
  await page.getByText('Import a donor CSV instead', {exact: true}).click();
  await page.getByLabel('Donor CSV file').setInputFiles({name: 'journey.csv', mimeType: 'text/csv', buffer: Buffer.from(`${header}\n${donation('Replan vegetables')}`)});
  await page.getByLabel('Select CSV row 2').check();
  await page.getByRole('button', {name: 'File selected rows (1)'}).click();
  await expect(page.getByRole('heading', {name: 'Replan vegetables', exact: true})).toBeVisible();
  const runResponse = page.waitForResponse(r => r.url().endsWith('/run') && r.request().method() === 'POST');
  await page.getByRole('button', {name: 'Work out the split'}).click();
  const first: Workspace = await (await runResponse).json();
  const row = first.offers.find(o => o.offer.title === 'Replan vegetables')!;
  const original = row.plan!;
  await page.getByLabel(/I have reviewed this exact allocation/).check();
  await page.getByRole('button', {name: 'Approve in sandbox'}).click();
  await expect(page.getByRole('heading', {name: 'The recorded plan'})).toBeVisible();
  await page.getByLabel('Pickup organisation').selectOption(JSON.stringify(['Omonoia Soup Kitchen', original.digest]));
  await page.getByRole('button', {name: 'Claim this share'}).click();
  await expect(page.getByText('Claimed', {exact: true})).toBeVisible();
  await page.getByText('Rehearse a collection disruption', {exact: true}).click();
  await page.getByLabel('Organisation affected').selectOption('Omonoia Soup Kitchen');
  await page.getByLabel('New collection capacity (kg)').fill('0');
  await page.getByRole('button', {name: 'Record simulated disruption'}).click();
  await expect(page.getByText('Old allocation is no longer actionable.', {exact: false})).toBeVisible();
  await expect(page.getByRole('button', {name: 'Approve in sandbox'})).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('region', {name: 'Before and after disruption'})).toContainText('Omonoia Soup Kitchen');
  const nextResponse = page.waitForResponse(r => r.url().endsWith('/run') && r.request().method() === 'POST');
  await page.getByRole('button', {name: 'Re-run the fleet'}).click();
  const next: Workspace = await (await nextResponse).json();
  const replanned = next.offers.find(o => o.offer.id === row.offer.id)!;
  expect(replanned.plan!.digest).not.toBe(original.digest);
  expect(replanned.result.draft_barred_because!['Omonoia Soup Kitchen']).toContain('capacity is zero');
  expect(replanned.replan!.before_digest).toBe(original.digest);
  expect(next.pickups.some(p => p.state === 'invalidated')).toBe(true);
  await expect(page.getByLabel(/I have reviewed this exact allocation/)).not.toBeChecked();
  await expect(page.getByRole('button', {name: 'Approve in sandbox'})).toBeDisabled();
  await expect(page.getByText(/not universal or certified fairness/)).toBeVisible();
  await page.screenshot({path: info.outputPath('before-after-replan.png'), fullPage: true});
  await page.getByLabel(/I have reviewed this exact allocation/).check();
  const approvalResponse = page.waitForResponse(r => r.url().endsWith('/approve') && r.request().method() === 'POST');
  await page.getByRole('button', {name: 'Approve in sandbox'}).click();
  const approved: Workspace = await (await approvalResponse).json();
  expect(approved.records).toHaveLength(2);
  expect(approved.records.find(r => r.content_digest === original.digest)?.superseded_by).toBeTruthy();
  const pickup = approved.pickups.find(p => p.offer_id === row.offer.id && p.state === 'unclaimed')!;
  await page.getByLabel('Pickup organisation').selectOption(JSON.stringify([pickup.org, pickup.commitment_digest || pickup.plan_digest]));
  await page.getByRole('button', {name: 'Claim this share'}).click();
  await expect(page.getByText('Claimed', {exact: true})).toBeVisible();
  const future = await page.evaluate(() => { const d = new Date(Date.now() + 3600_000); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`; });
  await page.getByLabel('Collection time (your local time)').fill(future);
  await page.getByRole('button', {name: 'Save collection time'}).click();
  await expect(page.getByText('Scheduled', {exact: true})).toBeVisible();
  await page.getByLabel('This collection actually happened in the simulation.').check();
  await page.getByRole('button', {name: 'Confirm collection'}).click();
  await expect(page.getByText('Simulation confirmed', {exact: true})).toBeVisible();
  await page.getByText('Pickup manifest · copy or download', {exact: true}).click();
  await expect(page.getByLabel('Pickup manifest', {exact: true})).toContainText(original.digest);
  await expect(page.getByLabel('Pickup manifest', {exact: true})).toContainText('Human/coordinator proof NOT_RUN');
  await page.getByRole('button', {name: 'Copy pickup manifest'}).click();
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('Isolated simulation');
  const download = page.waitForEvent('download');
  await page.getByRole('button', {name: 'Download pickup manifest'}).click();
  expect((await download).suggestedFilename()).toBe('merismos-pickup-manifest.txt');
  await info.attach('replan-runtime.json', {body: JSON.stringify({before: original.digest, after: replanned.plan!.digest, comparison: replanned.replan, records: approved.records}), contentType: 'application/json'});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path: info.outputPath('replan-pickup-manifest.png'), fullPage: true});
});
