import { expect, test } from '@playwright/test';

test('ME01/02/03: exact sandbox approval, persistent claim, scheduled and confirmed collection', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Offers', exact: true })).toBeVisible();
  await expect(page.getByText('Synthetic demo', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'End of day bread and vegetables', exact: true }).click();
  await page.getByRole('button', { name: 'Work out the split' }).click();
  await expect(page.getByRole('heading', { name: 'Approve this exact plan' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Omonoia Soup Kitchen' })).toBeVisible();
  await expect(page.getByText('124 kg', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Approve in sandbox' })).toBeDisabled();
  await page.getByText('Read the exact record text', { exact: true }).click();
  await expect(page.locator('pre')).toContainText('Elpida');
  await expect(page.getByLabel('Shareable reasons summary')).toContainText('DRAFT');
  await page.screenshot({ path: info.outputPath('approval.png'), fullPage: true });
  await page.getByLabel('I have reviewed this exact allocation and record address, and approve this plan.').check();
  await page.getByRole('button', { name: 'Approve in sandbox' }).click();
  await expect(page.getByRole('heading', { name: 'The recorded plan' })).toBeVisible();
  await page.getByRole('link', { name: 'Open collection tasks →' }).click();
  const kitchen = page.getByRole('article').filter({has: page.getByRole('heading', {name: 'Omonoia Soup Kitchen'})});
  await kitchen.getByRole('combobox', { name: 'Collecting role', exact: true }).selectOption('kitchen lead');
  await kitchen.getByRole('button', { name: 'Claim this share' }).click();
  await expect(kitchen.getByText('Claimed', { exact: true })).toBeVisible();
  await page.reload();
  await expect(kitchen.getByText('Collecting role: kitchen lead')).toBeVisible();
  const tomorrow = new Date(Date.now() + 86400_000).toISOString().slice(0, 16);
  await kitchen.getByLabel('Collection time (your local time)').fill(tomorrow);
  await kitchen.getByRole('button', { name: 'Save collection time' }).click();
  await expect(kitchen.getByText('Scheduled', { exact: true })).toBeVisible();
  await expect(kitchen.getByRole('button', { name: 'Confirm collection' })).toBeDisabled();
  await kitchen.getByLabel('This collection actually happened in the simulation.').check();
  await kitchen.getByRole('button', { name: 'Confirm collection' }).click();
  await page.getByLabel('Show').selectOption('confirmed');
  await expect(kitchen.getByText('Confirmed collected')).toBeVisible();
  await expect(kitchen.getByRole('button', { name: 'Claim this share' })).toHaveCount(0);
  await page.screenshot({ path: info.outputPath('confirmed-pickup.png'), fullPage: true });
  await page.getByRole('link', { name: 'Published history', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Sandbox history' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'records/offer-4471.md' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('link', { name: 'records/offer-4471.md' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(await page.evaluate(() => Object.keys(localStorage).sort())).toEqual(['merismos.session']);
  expect(errors).toEqual([]);
});

test('Safety refusal, empty filters, deep link and live read-only boundary', async ({ page }, info) => {
  await page.goto('/#/offers/offer-4477');
  await page.getByRole('button', { name: 'Work out the split' }).click();
  await expect(page.getByText('Safety refusal', { exact: true }).first()).toBeVisible();
  await expect(page.getByRole('button', { name: 'Approve in sandbox' })).toHaveCount(0);
  await page.screenshot({ path: info.outputPath('refusal.png'), fullPage: true });
  await page.getByRole('link', { name: 'All offers' }).click();
  await page.getByRole('searchbox', { name: 'Search offers' }).fill('no such donation');
  await expect(page.getByRole('heading', { name: 'No offers match' })).toBeVisible();
  await page.getByLabel('Workspace', { exact: true }).selectOption('live');
  await expect(page.getByRole('heading', { name: 'Offers', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'End of day bread and vegetables', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Work out the split' })).toBeDisabled();
  await expect(page.getByText(/Live changes require an authenticated/)).toBeVisible();
  await expect(page.getByText('Synthetic demo', { exact: true })).toBeVisible();
});

test('Real HTTP contract rejects stale consent, session crossover and duplicate collection', async ({ request }) => {
  const create = await request.post('/api/sessions', {data: {}});
  const {session} = await create.json();
  const headers = {'X-Merismos-Session': session};
  const read = async () => (await request.get('/api/workspace?mode=sandbox', {headers})).json();
  let state = await read();
  const send = (kind: string, data: Record<string, unknown>) => request.post(`/api/offers/offer-4471/${kind}`, {headers, data: {...data, mode:'sandbox', version:state.version, request_id:crypto.randomUUID()}});
  const run = await send('run', {}); expect(run.ok()).toBe(true); state = await run.json();
  const plan = state.offers.find((o: {offer: {id: string}}) => o.offer.id === 'offer-4471').plan;
  expect((await send('approve', {...plan, consent:false})).status()).toBe(400);
  expect((await send('approve', {...plan, digest:'changed', consent:true})).status()).toBe(409);
  expect((await request.get('/api/workspace?mode=sandbox', {headers:{'X-Merismos-Session':'x'.repeat(43)}})).status()).toBe(410);
  const approved = await send('approve', {...plan, consent:true}); expect(approved.ok()).toBe(true); state = await approved.json();
  const org = 'Omonoia Soup Kitchen';
  const claimed = await send('pickup', {...plan, org, role:'duty manager', action:'claim'}); expect(claimed.ok()).toBe(true); state = await claimed.json();
  const confirmed = await send('pickup', {...plan, org, action:'confirm', consent:true}); expect(confirmed.ok()).toBe(true); state = await confirmed.json();
  expect((await send('pickup', {...plan, org, action:'confirm', consent:true})).status()).toBe(409);
  expect((await send('run', {})).status()).toBe(409);
});
