import { expect, test } from '@playwright/test';
import type { Workspace } from '../src/types';

test('ME09: dashboard metrics, unit drilldowns, search focus, back and reload preserve context', async ({ page }, info) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible();
  const metrics = page.getByRole('region', { name: 'Workspace metrics' });
  await expect(metrics.getByRole('link')).toHaveCount(6);
  await expect(metrics.getByRole('link', { name: /^Allocated in computed plans/ })).toContainText('Unknown');
  await expect(metrics.getByRole('link', { name: /^Confirmed collections/ })).toContainText('0');
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(11, 15, 30)');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('dashboard.png'), fullPage: true });
  await page.getByLabel('Metric unit').selectOption('units');
  await expect(metrics.getByRole('link', { name: /^Offered/ })).toContainText('180 units');
  await metrics.getByRole('link', { name: /^Offered/ }).click();
  await expect(page.getByRole('heading', { name: 'Records', exact: true })).toBeFocused();
  await expect(page.getByLabel('Unit', { exact: true })).toHaveValue('units');
  await expect(page.locator('.record-cards')).not.toContainText(' kg');
  const search = page.getByRole('searchbox', { name: 'Search offers' });
  await search.pressSequentially('grocery');
  await expect(search).toHaveValue('grocery'); await expect(search).toBeFocused();
  await expect(page).toHaveURL(/q=grocery/);
  await page.reload(); await expect(search).toHaveValue('grocery');
  await search.fill('');
  await page.getByRole('link', { name: 'Review evidence & dispatch →' }).click();
  await expect(page).toHaveURL(/offer=offer-4483/);
  await expect(page.getByRole('heading', { name: 'Assorted ambient grocery, end of line', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Work out the split' })).toBeVisible();
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'History' }).click();
  await expect(page).toHaveURL(/history\?offer=offer-4483/);
  await expect(page.getByRole('heading', { name: 'Sandbox history', exact: true })).toBeVisible();
  await page.goBack(); await expect(page).toHaveURL(/workspace\?offer=offer-4483/);
  await expect(page.getByRole('heading', { name: 'Assorted ambient grocery, end of line', exact: true })).toBeVisible();
  await page.reload(); await expect(page.getByRole('button', { name: 'Work out the split' })).toBeVisible();
  await expect(page.locator('.decision-context')).toContainText('offer-4483');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('ME10: integrated exact decision and independent pickup selection, screenshots and metric reconciliation', async ({ page }, info) => {
  await page.goto('/#/workspace?offer=offer-4471');
  await page.getByRole('button', { name: 'Work out the split' }).click();
  await expect(page.getByRole('heading', { name: 'Approve this exact plan' })).toBeVisible();
  await page.screenshot({ path: info.outputPath('selected-workspace.png'), fullPage: true });
  const consent = page.getByLabel(/I have reviewed this exact allocation/);
  await consent.check();
  await page.locator('.offer-select').filter({ hasText: 'Assorted ambient grocery, end of line' }).click();
  await expect(page.getByRole('heading', { name: 'Assorted ambient grocery, end of line', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Approve in sandbox' })).toHaveCount(0);
  await page.locator('.offer-select').filter({ hasText: 'End of day bread and vegetables' }).click();
  await expect(page.getByRole('heading', { name: 'End of day bread and vegetables', exact: true })).toBeVisible();
  await expect(consent).not.toBeChecked();
  await consent.check(); await page.getByRole('button', { name: 'Approve in sandbox' }).click();
  const dispatch = page.getByRole('region', { name: 'Selected offer pickups' });
  await expect(dispatch.getByText('Needs a collector', { exact: true })).toBeVisible();
  const selectedPickup = await dispatch.getByLabel('Pickup organisation').inputValue();
  await expect(page).toHaveURL(/pickup=/);
  await expect(dispatch.getByText('Confirmed collected')).toHaveCount(0);
  await dispatch.getByRole('button', { name: 'Claim this share' }).click();
  await expect(dispatch.getByText('Claimed', { exact: true })).toBeVisible();
  await dispatch.getByLabel(/This collection actually happened/).check();
  await dispatch.getByRole('button', { name: 'Confirm collection' }).click();
  await expect(dispatch.getByText('Confirmed collected')).toBeVisible();
  await expect(dispatch.getByRole('button', { name: 'Claim this share' })).toHaveCount(0);
  const session = await page.evaluate(() => localStorage.getItem('merismos.session'));
  const response = await page.request.get('/api/workspace?mode=sandbox', { headers: { 'X-Merismos-Session': session! } });
  expect(response.status()).toBe(200);
  const state: Workspace = await response.json();
  const confirmed = state.pickups.filter(p => p.state === 'confirmed');
  expect(confirmed).toHaveLength(1);
  expect(confirmed[0].confirmed_at).toEqual(expect.any(Number));
  const pending = state.pickups.filter(p => ['unclaimed', 'claimed', 'scheduled', 'overdue'].includes(p.state));
  expect(pending).toHaveLength(1);
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Dashboard' }).click();
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible();
  const metrics = page.getByRole('region', { name: 'Workspace metrics' });
  await expect(metrics.getByRole('link', { name: /^Allocated in computed plans/ })).toContainText('116 kg');
  await expect(metrics.getByRole('link', { name: /^Unallocated in computed plans/ })).toContainText('124 kg');
  await expect(metrics.getByRole('link', { name: /^Confirmed collections/ })).toContainText(String(confirmed.length));
  await metrics.getByRole('link', { name: /^Pending pickups/ }).click();
  await expect(page.getByRole('heading', { name: 'Records', exact: true })).toBeVisible();
  await expect(page.getByLabel('Record filter')).toHaveValue('pending');
  await expect(page.locator('.record-cards article')).toHaveCount(1);
  await page.getByRole('link', { name: 'Return to workspace →' }).click();
  await expect(page.getByRole('heading', { name: 'End of day bread and vegetables', exact: true })).toBeVisible();
  await expect(page.locator('.decision-context')).toContainText('offer-4471');
  await page.reload(); await expect(dispatch.getByText('Confirmed collected')).toBeVisible();
  await expect(dispatch.getByLabel('Pickup organisation')).toHaveValue(selectedPickup);
  await expect(dispatch.getByRole('button', { name: 'Claim this share' })).toHaveCount(0);
  await page.screenshot({ path: info.outputPath('selected-workspace-collected.png'), fullPage: true });
});

test('ME11: real offline interruption pauses mutations and refresh recovers without duplicate writes', async ({ page, context }) => {
  await page.goto('/#/workspace?offer=offer-4471');
  await expect(page.getByRole('button', { name: 'Work out the split' })).toBeVisible();
  const session = await page.evaluate(() => localStorage.getItem('merismos.session'));
  await context.setOffline(true);
  await page.getByRole('button', { name: 'Work out the split' }).click();
  await expect(page.getByRole('alert')).toContainText('Actions are paused');
  await expect(page.locator('.action-card button')).toBeDisabled();
  await expect(page.getByText(/saved view may be stale/)).toBeVisible();
  await context.setOffline(false);
  await page.getByRole('button', { name: 'Refresh and review' }).click();
  await expect(page.getByRole('alert')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Work out the split' })).toBeEnabled();
  const response = await page.request.get('/api/workspace?mode=sandbox', { headers: { 'X-Merismos-Session': session! } });
  expect(response.status()).toBe(200);
  const state: Workspace = await response.json();
  expect(state.records).toHaveLength(0);
  expect(state.pickups).toHaveLength(0);
  expect(state.offers.find(row => row.offer.id === 'offer-4471')!.status).toBe('not_started');
});

test('ME12: expired session and missing offer recover without selecting another decision silently', async ({ page }) => {
  await page.goto('/#/workspace?offer=offer-999999');
  await expect(page.getByRole('heading', { name: 'Offer not found' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Approve in sandbox' })).toHaveCount(0);
  await page.evaluate(() => localStorage.setItem('merismos.session', 'x'.repeat(43)));
  await page.reload();
  await expect(page.getByRole('alert')).toContainText('expired');
  await page.getByRole('button', { name: 'Start a new sandbox' }).click();
  await expect(page.getByRole('heading', { name: 'Offer not found' })).toBeVisible();
  await page.locator('.offer-select').filter({ hasText: 'End of day bread and vegetables' }).click();
  await expect(page.getByRole('heading', { name: 'End of day bread and vegetables', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Work out the split' })).toBeEnabled();
});
